-- EuCAP Community Annotation Schema v2
-- This schema stores the data from the community annotator submitted through
-- the EuCAP web tool or the email submission pipeline.
-- The schema was generated by phpMyAdmin.
-- $Id: eucap_schema.sql 537 2012-01-06 10:15:34Z vkrishna $
-- $Id: eucap_schema.sql 537 2007-07-24 00:06:34Z hamilton $

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: 'community_annotation'
--

-- --------------------------------------------------------

--
-- Table structure for table 'family'
--

CREATE TABLE v2_family (
  family_id int(10) unsigned NOT NULL auto_increment,
  user_id int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  gene_class_symbol varchar(30) NOT NULL,
  symbol_name mediumtext,
  description mediumtext,
  source mediumtext,
  is_public tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (family_id),
  KEY user_id (user_id),
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='gene family information';

-- --------------------------------------------------------

--
-- Table structure for table 'loci'
--

CREATE TABLE v2_loci (
  locus_id int(10) unsigned NOT NULL auto_increment,
  user_id int(10) unsigned NOT NULL,
  family_id int(10) unsigned NOT NULL,
  gene_locus varchar(30),
  orig_func_annotation mediumtext,
  gene_symbol varchar(30),
  func_annotation mediumtext,
  gb_genomic_acc varchar(100) default NULL,
  gb_cdna_acc varchar(100) default NULL,
  gb_protein_acc varchar(100) default NULL,
  mutant_phenotype mediumtext default NULL,
  allelism_data mediumtext default NULL,
  reference_lab mediumtext default NULL,
  reference_pub mediumtext default NULL,
  mod_date datetime,
  `comment` mediumtext,
  has_structural_annot tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (locus_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='community annotation for each locus';

-- --------------------------------------------------------

--
-- Table structure for table 'allele'
--

-- --------------------------------------------------------

CREATE TABLE v2_alleles (
  allele_id int(10) unsigned NOT NULL auto_increment,
  locus_id int(10) unsigned NOT NULL,
  allele_name varchar(30),
  alt_allele_name varchar(30) default NULL,
  reference_lab mediumtext,
  has_altered_phenotype tinyint(1) NOT NULL default '0',
  PRIMARY_KEY  (allele_id),
  KEY locus_id (locus_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='allele specific information';

--
-- Table structure for table 'sessions'
--

CREATE TABLE v2_sessions (
  id char(32) NOT NULL,
  a_session text NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='CGI::Session session storage table';

-- --------------------------------------------------------

--
-- Table structure for table 'structural_annotation'
--

CREATE TABLE v2_structural_annot (
  sa_id int(10) unsigned NOT NULL auto_increment,
  locus_id int(10) unsigned NOT NULL,
  model mediumtext,
  is_finished tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (sa_id),
  KEY locus_id (locus_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='structural annotation storage';

-- --------------------------------------------------------

--
-- Table structure for table 'users'
--

CREATE TABLE users (
  user_id int(10) unsigned NOT NULL auto_increment,
  `name` varchar(100) NOT NULL,
  username varchar(20) NOT NULL,
  salt char(8) NOT NULL,
  `hash` char(22) NOT NULL,
  email varchar(100) default NULL,
  organization varchar(100) default NULL,
  url varchar(100) default NULL,
  PRIMARY KEY  (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='community annotation users';

--
-- Constraints for dumped tables
--

--
-- Constraints for table `v2_family`, `v2_loci`, `v2_alleles` and `v2_structural_annot`
--
ALTER TABLE `v2_family`
  ADD CONSTRAINT v2_family_ibfk_1 FOREIGN KEY (user_id) REFERENCES v2_users (user_id);

ALTER TABLE `v2_loci`
  ADD CONSTRAINT v2_loci_ibfk_1 FOREIGN KEY (family_id) REFERENCES v2_family (family_id),
  ADD CONSTRAINT v2_loci_ibfk_2 FOREIGN KEY (user_id) REFERENCES v2_users (user_id);

ALTER TABLE `v2_alleles`
  ADD CONSTRAINT v2_alleles_ibfk_1 FOREIGN KEY (locus_id) REFERENCES v2_loci (locus_id);

ALTER TABLE `v2_structural_annot`
  ADD CONSTRAINT v2_struct_annot_ibfk_1 FOREIGN KEY (locus_id) REFERENCES v2_loci (locus_id);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
