-- EuCAP Community Annotation Schema
-- This schema stores the data from the community annotator submitted through
-- the EuCAP web tool or the email submission pipeline. 
-- The schema was generated by phpMyAdmin.
-- $Id: eucap_schema.sql 537 2007-07-24 00:06:34Z hamilton $

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

-- 
-- Database: 'community_annotation'
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table 'family'
-- 

CREATE TABLE family (
  family_id int(10) unsigned NOT NULL auto_increment,
  user_id int(10) unsigned NOT NULL,
  superfamily_id int(10) unsigned default NULL,
  `name` varchar(255) NOT NULL,
  description mediumtext,
  criteria mediumtext,
  source mediumtext,
  footer mediumtext,
  is_public tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (family_id),
  KEY user_id (user_id),
  KEY superfamily_id (superfamily_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='gene family information';

-- --------------------------------------------------------

-- 
-- Table structure for table 'loci'
-- 

CREATE TABLE loci (
  locus_id int(10) unsigned NOT NULL auto_increment,
  user_id int(10) unsigned NOT NULL,
  family_id int(10) unsigned NOT NULL,
  locus_name varchar(30) NOT NULL,
  original_annotation varchar(255) default NULL,
  gene_name varchar(255) default NULL,
  alt_gene_name varchar(255) default NULL,
  gene_description varchar(255) default NULL,
  genbank_genomic_acc varchar(100) default NULL,
  genbank_cdna_acc varchar(100) default NULL,
  genbank_protein_acc varchar(100) default NULL,
  mutant_info varchar(255) default NULL,
  `comment` mediumtext,
  has_structural_annotation tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (locus_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='community annotation for each locus';

-- --------------------------------------------------------

-- 
-- Table structure for table 'sessions'
-- 

CREATE TABLE sessions (
  id char(32) NOT NULL,
  a_session text NOT NULL,
  PRIMARY KEY  (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='CGI::Session session storage table';

-- --------------------------------------------------------

-- 
-- Table structure for table 'structural_annotation'
-- 

CREATE TABLE structural_annotation (
  sa_id int(10) unsigned NOT NULL auto_increment,
  locus_id int(10) unsigned NOT NULL,
  model mediumtext,
  is_finished tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (sa_id),
  KEY locus_id (locus_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='structural annotation storage';

-- --------------------------------------------------------

-- 
-- Table structure for table 'superfamily'
-- 

CREATE TABLE superfamily (
  superfamily_id int(10) unsigned NOT NULL auto_increment,
  user_id int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  description mediumtext,
  source mediumtext,
  PRIMARY KEY  (superfamily_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='superfamily information';

-- --------------------------------------------------------

-- 
-- Table structure for table 'users'
-- 

CREATE TABLE users (
  user_id int(10) unsigned NOT NULL auto_increment,
  `name` varchar(100) NOT NULL,
  username varchar(20) NOT NULL,
  salt char(8) NOT NULL,
  `hash` char(22) NOT NULL,
  email varchar(100) default NULL,
  organization varchar(100) default NULL,
  url varchar(100) default NULL,
  PRIMARY KEY  (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='community annotation users';

-- 
-- Constraints for dumped tables
-- 

-- 
-- Constraints for table `family`
-- 
ALTER TABLE `family`
  ADD CONSTRAINT family_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (user_id),
  ADD CONSTRAINT family_ibfk_2 FOREIGN KEY (superfamily_id) REFERENCES superfamily (superfamily_id);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
